splinted reducer logic
htmlacademy-react/1811791-what-to-watch-8 pull request #10
Opened 2021-11-12 19:59 UTC by Volnodoom

2021-11-13 10:37 UTC, bini1988 requested changes
Разбиение на редюсеры выглядит круто, давай пойдем дальше и добавим в приложение [функции-селекторы](https://redux.js.org/usage/deriving-data-selectors#basic-selector-concepts) и логику по фильтрации и получения списка жанров вынесим в отдельные функции-селекторы

2021-11-13 10:37 UTC, bini1988 commented on project/src/components/app/app.tsx
> +  isDataLoaded: USER.isDataLoaded,
Давай вынесем всю логику извлечения данных в [функции селекторы](https://redux.js.org/usage/deriving-data-selectors#deriving-data):
```js
  films: getFilms(state),
  authorizationStatus:  getAuthorizationStatus(state),
  isDataLoaded: isDataLoaded(state),
```
Это скроет детали реализации store и позволит избавиться от дублирования логики в mapStateToProps

2021-11-13 10:37 UTC, bini1988 commented on project/src/components/general/avatar.tsx
> +  authorizationStatus: USER.authorizationStatus,
Тогда в каждом `mapStateToProps` можно будет использовать общий набор функций-селекторов

2021-11-13 10:37 UTC, bini1988 commented on project/src/components/general/catalog-movie-thumbnails.tsx
> +  const getActiveFilm = useCallback(() => setActiveFilm, []);
Нет смысла использовать `useCallback` или `useMemo` с возвращаемыми `useState` функциями, React гаратирует нам что `useState` будет возвращать ссылку на одну и туже функцию

2021-11-13 10:37 UTC, bini1988 commented on project/src/components/general/footer.tsx
> +        <p>© 2021 What to watch Ltd.</p>
Обычно в таких случая пишут что-то вроде `(new Date()).getFullYear()`

2021-11-13 10:37 UTC, bini1988 commented on project/src/store/films-data/films-data.ts
> +  filtratedFilms: [],
А почему это поле в 2х редюсерах одновременно?

2021-11-13 10:37 UTC, bini1988 commented on project/src/store/user-process/user-process.ts
> +  isDataLoaded: false,
Кажется что `isDataLoaded` больше имеет отношение к получению данных по фильмам а не к пользователю

2021-11-13 10:37 UTC, bini1988 commented on project/src/store/films-process/films-process.ts
> +  activeGenre: ALL_GENRES,
Я предлагаю упростить код избавиться от этого редюсера, а всб логику фильтрации и получения списка жанров вынести в [функции-селекторы](https://redux.js.org/usage/deriving-data-selectors#calculating-derived-data-with-selectors):

```js
export const getFilmsByGenre(state, genre) {
  const fimls = getFilms(state);
   /* Логика возвращающая отфильтрованный список фильмов */
}
export const getFilmsGenres(state) {
  const fimls = getFilms(state);
   /* Логика возвращающая список жанров */
}
```

Данные селекторы можно использвать в `mapStateToProps`, плюс хорошо бы использовать для данных селекторов [reselect](https://redux.js.org/usage/deriving-data-selectors#writing-memoized-selectors-with-reselect) для оптимизации их перевычисления при изменений списка фильмов

2021-11-13 16:10 UTC, Volnodoom commented on project/src/components/general/catalog-movie-thumbnails.tsx
> +  const getActiveFilm = useCallback(() => setActiveFilm, []);
Коль но если я это не делаю, то у меня все превьюхи перересовываются при наведении на одно из оконо, можешь посмотреть убрать этот юзКолбекю и обратить внимание как все это начинает перерисовывается в профайлере

2021-11-13 19:28 UTC, bini1988 commented on project/src/components/general/catalog-movie-thumbnails.tsx
> +  const getActiveFilm = useCallback(() => setActiveFilm, []);
Текущий вариант не является решение проблемы, пому-что код сломан:

```js
const getActiveFilm = useCallback(() => setActiveFilm, []);
```

здесь `useCallback` вернет функцию, которая при вызове будет возвращать **значение** `setActiveFilm`, тоесть функция  `setActiveFilm` в данном случае просто **нигода** не вызовется, поэтому и "пропадает" ререндер компонента `CatalogMovieThumbnails` при такой записи (можно в этом убедиться вызывав `getActiveFilm(666)` и проверив изменится ли значение `activeFilm`). В целом использование здесь данного `useState` не имеет смысла поскольку значение `activeFilm` нигде не используется, а значит и `getActiveFilm` и `useState` можно просто удалить.

Если всетаки  `activeFilm` бы использоватлся и `setActiveFilm` передавался в компоненты списка как есть, то все элементы списка действительно бы перерисовывались поскольку вызов `setActiveFilm` приводил бы к перерендеру комопнента `CatalogMovieThumbnails` и всех его вложенных функциональных комопнетов. В таком случае ререндер можно оптимизировать путем оборачивания компонента `MovieThumbnails` в React.memo.

```js
export default memo(MovieThumbnails);
```

Тогда React начнет проверять изменились ли props компонента MovieThumbnails и делать его ререндер только в случае изменений.

2021-11-15 18:50 UTC, bini1988 requested changes
Нужно исправить ошибки eslint

2021-11-15 18:50 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +  const [activeFilm, setActiveFilm] = useState<number | null>(null);
В коде не должно быть eslint-disable, если эта переменная не используется нужно удалить этот код

2021-11-15 18:50 UTC, bini1988 commented on project/src/components/general/catalog-movie-thumbnails.tsx
> +  const getActiveFilm = useCallback(() => setActiveFilm, []);
Давай удалим этот код, он ничего не делает, а на проверке к нему могут возникнуть вопросы

2021-11-15 18:50 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +        {Array.from(genreList)
`genreList` уже массив, плюс `slice(0,8)` я бы предложим перенести в getGenreList селектор

2021-11-15 18:50 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +            ))}
Давай избавимся тут от дублирования верстки, тут достаточно одного `map`, проще всего чтобы `filmsByGenre` возвращал весь список фильмов для  `undefined` и `ALL_GENRES`

2021-11-18 17:02 UTC, bini1988 requested changes
Нужно поправить формат времени и анимировать ползунок

2021-11-18 17:02 UTC, bini1988 commented on project/src/components/player/player.tsx
> +            {getTimeForPlayer(totalTime, currentTime)}
Формат времени -MM:SS или -HH:MM:SS тоесть вместо `-1:9` должно быть `-01:09`

2021-11-19 10:32 UTC, bini1988 approved these changes

2021-11-19 10:32 UTC, merged