Module2 task1
htmlacademy-react/1811791-what-to-watch-8 pull request #2
Opened 2021-10-05 00:11 UTC by Volnodoom

2021-10-05 07:10 UTC, bini1988 requested changes
Нужно исправить замечания линтера и нейминг компонентов и их использование через jsx

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/general/top-cover.tsx
> +function TopCover({wtwHidden, isLogged} : TopCoverProps): JSX.Element {
Вот здесь props объявлены кореектно

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/general/top-cover.tsx
> +  }
Аналогично, я бы не выносил этот код в отдельную функцию или компонент:
```tsx
{wtwHidden && <h1 className="visually-hidden">WTW</h1>}
```
выглядит короче и ясней, плюс если обявляется функци с большой буквы то подразумевается что это React компонент (особенно в React проектах) а значит он должен быть вынесен в отдельный файл и использваться с помощью jsx:
```tsx
{wtwHidden && <WTWHiddenState/>}
```
если обявляется функция котороя просто возвращает jsx верстку то ее как правило именуют как:
```ts
function rendeTitle() { return <></>; }
```

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +const genreFilterFrames = [
Лучше сразу вынести все mock данные в отдельную папку `mocks`

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +  function filterTemplate({filterGenre, filterUrl}: filterTemplateProps, keyId: number):JSX.Element {
Нужно определиться является ли это React комопнентом или функцией?

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +  function filterTemplate({filterGenre, filterUrl}: filterTemplateProps, keyId: number):JSX.Element {
Плюс я бы не стал выносить это в отдельный метод, это усложняет чтение кода вынужная скакать по файлу сверху вниз и снова на верх

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-movie-catalog.tsx
> +function MovieCatalog(film:MovieProps, keyInd: number): JSX.Element {
Имя компонента должно совпадать с именем файла, полюс поправить объект пропсов

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-movie-frame.tsx
> +function MainMovieFrame(film: MovieProps): JSX.Element {
Попроавить props

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-page-content.tsx
> +function PageContent(film: MovieProps): JSX.Element {
Имя компонента + props

2021-10-05 07:10 UTC, bini1988 commented on project/src/components/main/main-page-content.tsx
> +            .map((line, index) => MovieCatalog(film, index))}
Должен быть вызов через jsx

2021-10-05 16:41 UTC, Volnodoom commented on project/src/components/main/main-genre-filters.tsx
> +const genreFilterFrames = [
Коль, а почему ты говоришь о моках (для genreFilterFrames)? возможно ты имел ввиду константы?

2021-10-09 10:37 UTC, bini1988 approved these changes

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/const/types.ts
> +export type MovieInfo = {
Я бы выносил все типы в отдельную директорию `project/src/types/types.ts`

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/const/const.ts
> +export const Poster = {
Не совсем понятна цель файла `const.ts` на уровне `project/src/components`, кажется это потенциальная солянка всех констант всех компонентов, но не ясно для чего их смешивать в одном файле?

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/avatar.tsx
> +              <img src={AvatarAdjustment.Img} alt={AvatarAdjustment.AltImg}  width={AvatarAdjustment.Width}  height={AvatarAdjustment.Height}  />
А для чего выносить здесь значения в константы? Часть данных сюда будет попадать через пропс user (описан как User в тех задании), а width и height просто константы их можно оставить в верстке как есть.

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/avatar.tsx
> +const SING_OUT = 'Sign out';
Тоже не совсем понять для чего выносить эти константы? Так иногда делают если понимают что в ближайшем будущем этот код будет меняться и расширятся, но сейчас я бы пока руководствовался правилом чем проще и короче код тем лучше.

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/background-poster.tsx
> +function BackgroundPoster(props: {film: MovieInfo}):JSX.Element {
Тут главное не переборщить, есть критерий [Д25](https://up.htmlacademy.ru/react/8/criteries#d25) который требует все компоненты покрыть тестами, если разбивать на совсем маленькие компоненты, то количество появляющегося в таком случае кода будет нивелировать всю пользу от таких компонентов, исключение, если этот маленький компонент используется по всему проекту несколько раз.

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/big-picture.tsx
> +    <div className= {props.class}>
Лучше не использовать литерал `class` в React в таких случаях используется `className`

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/footer.tsx
> +      <Logo logoUrl={LogoUrl.Main} isTop= {LOGO_BOTTOM}/>
Кажется константа `LOGO_BOTTOM` тут лишняя, можно просто `<Logo logoUrl={LogoUrl.Main} isTop={true}/>`

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/logo.tsx
> +      <a href= {props.logoUrl} className= {props.isTop ? 'logo__link' : 'logo__link logo__link--light'}>
А почему пропс называет `isTop` а не `isLight` как css модификатор?

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/movie-card-buttons.tsx
> +      throw Error ('It is not possible to find this kind of Button in const');
Обычно просто дают props значения по умолчанию, не вижу причины кидать здесь ошибку которая может сломать все приложение

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/movie-card-buttons.tsx
> +    }
switch выглядит довольно громоздко, как вариант можно использовать объект:
```jsx
const PROPS_BY_KIND = {
[KindOfMovieCardButtons.Play]: {},
[KindOfMovieCardButtons.AddToMyList]: {}
}

function MovieCardButtons(props: {buttonKind: string}): JSX.Element {
  const {buttonKind} = props;
  const {ClassName, ViewBox, Use, Snap, Width, Height} = PROPS_BY_KIND[KindOfMovieCardButtons.AddToMyList] || {};

    return (
      <button className={ClassName} type="button">
        <svg viewBox={ViewBox}  width={Width}  height={Height} >
          <use xlinkHref= {Use}></use>
        </svg>
        <span>{Snap}</span>
      </button>
);
}

```

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/general/movie-thumbanail.tsx
> +        <img src={poster} alt={altPoster} width={Poster.SmallWidth} height={Poster.SmallHeight} />
Аналогично, для чего выносить здесь значения в константы?

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/main/main-genre-filters.tsx
> +const GenreState = {
Вот здесь в константе есть смысл, что еще хорошо, она остается в пределах компонента, там где она используется

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/main/main-movie-frame.tsx
> +      <Header film= {props.film} wtwHidden = {WTWHiddenLine.True} logoUrl= {LogoUrl.SignIn}/>
Лишние пробелы между `=`

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/main/main.tsx
> +const COPYRIGHT = '© 2019 What to watch Ltd.';
Аналогично, зачем выносить это в константы?

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/main/main.tsx
> +            <button className="catalog__button" type="button">Show more</button>
Здесь, например, `Show more` прекрасно работает без констант

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/movie-add-review/add-review-header.tsx
> +      <Logo logoUrl={LogoUrl.Main} isTop={LOGO_TOP}/>
Думаю от LOGO_TOP можно избавиться

2021-10-09 10:37 UTC, bini1988 commented on project/src/index.tsx
> +    <App film= {FilmData}/>;
Пробелы

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/sign-in/sign-in.tsx
> +      <SignInFooter />
Возникает вопрос, а здесь точно нужно было выносить содержимое в отдельные компоненты?

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/sign-in/sign-in-header.tsx
> +
Лишний перенос

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/sign-in/sign-in-header.tsx
> +      <Logo logoUrl= {LogoUrl.Main} isTop={LOGO_TOP} />
LOGO_TOP кажется лишней константой

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/sign-in/sign-in-footer.tsx
> +      <Logo logoUrl= {LogoUrl.Main} isTop= {LOGO_BOTTOM}/>
LOGO_BOTTOM кажется лишней константой

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/const/const.ts
> +export const LOGO_BOTTOM = false;
Имена констант должны быть интуитивно понятны, плюс очень редко определяют константы для false и true (кажется что никогда), чаще в них выносят более сложные логические условия
```
export const IS_LOGO_TOP = IS_MOBILE && IS_IE;
```

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/sign-in/sign-in-content.tsx
> +function SignInContent  (): JSX.Element {
Лишний пробел

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/mylist/mylist.tsx
> +
А так ли нужны эти компоненты? Кажется они вполне могли бы уместиться внутри `Mylist`

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/mylist/mylist-header.tsx
> +      <Logo logoUrl={LogoUrl.Main} isTop={LOGO_TOP}/>
LOGO_TOP лишняя константа

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/mylist/mylist-footer.tsx
> +      <Logo logoUrl={LogoUrl.Main} isTop= {LOGO_BOTTOM}/>
LOGO_BOTTOM лишняя константа

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/mylist/mylist-content.tsx
> +  );
Кажется это точно нет смысла выносить в отдельный компонент

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/movie-card/movie-overview.tsx
> +
Лишние переносы необходимо удалять

2021-10-09 10:37 UTC, bini1988 commented on project/src/components/movie-card/movie-card.tsx
> +          <Header film= {props.film} wtwHidden={WTWHiddenLine.True} logoUrl= {LogoUrl.Main} />
Нет смысла выносить `true` и `false` в констаты

2021-10-09 12:13 UTC, merged