last Supervisor remarks took into account. Updated logic for sign up
htmlacademy-react/1811791-what-to-watch-8 pull request #9
Opened 2021-11-07 19:56 UTC by Volnodoom

2021-11-08 13:02 UTC, bini1988 requested changes
Форма логина не логинит пользоателя с логином `user@mail.ru` и паролем `123`, нужно поправить

2021-11-08 13:02 UTC, bini1988 commented on project/src/components/sign-in/sign-in.tsx
> +        spaceForPassword: !!passwordValue.match(/\s/),
Можно упростить до `!loginValue.trim()`

2021-11-11 21:24 UTC, Volnodoom commented on project/src/components/movie-card/movie-card.tsx
>    cardDemonstrate: string,
Не могу понять комментарий "Может здесь явно указать тип CardState ?". Можешь объяснить, какую мысль ты хочешь до меня донести?

2021-11-11 21:34 UTC, Volnodoom commented on project/src/components/sign-in/sign-in.tsx
> +        containMinimumPasswordText: !passwordValue.match(/[a-zа-я]/i),
Проверяют на наличие как минимум одной цифры и одной буквы

2021-11-11 21:35 UTC, Volnodoom commented on project/src/components/sign-in/sign-in.tsx
> +        containMinimumLoginText: !loginValue.match(/[a-zа-я]/i),
У меня все пропускает.

2021-11-11 21:40 UTC, Volnodoom commented on project/src/components/sign-in/sign-in.tsx
> +        containMinimumLoginText: !loginValue.match(/[a-zа-я]/i),
А касательно этого замечания форма ведет себя правильно)
"Форма логина не логинит пользоателя с логином user@mail.ru и паролем 123, нужно поправить"

о чем тебе и сообщает, что необходимы буквы)

2021-11-12 17:54 UTC, bini1988 commented on project/src/components/movie-card/movie-card.tsx
>    cardDemonstrate: string,
Я думал что CardState enum, если бы это было так то можно использовать его ка тип cardDemonstrate

2021-11-12 17:57 UTC, bini1988 commented on project/src/components/sign-in/sign-in.tsx
> +        containMinimumPasswordText: !passwordValue.match(/[a-zа-я]/i),
А если мой пароль `!!!!$$$`?

2021-11-12 18:05 UTC, merged